# Generated by Django 5.0.6 on 2024-05-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.CharField(default='Kassir', max_length=100),
        ),
    ]
